import './global.scss';
import { Header, INavigateList } from '@francesco-lucania-pizza/react-ui';
import StoreProvider from '../store/provider';

export const metadata = {
  title: 'Welcome to pizza-store',
  description: 'Generated by create-nx-workspace',
};

const navigationItems: INavigateList[] = [
  { name: 'Главная', uri: '/' },
  { name: 'Меню', uri: '/menu' },
  { name: 'Заказать', uri: '/order' },
  { name: 'Заказать', uri: '/order' },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Header
            navigate={navigationItems}
            logoPath="/img/logo.jpg"
            useNextLink={true}
          />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
