import './global.scss';
import { AppHeader } from './components/AppHeader/AppHeader';
import { Providers } from './components/Providers/Providers';

export const metadata = {
  title: 'Francesco Lucania Pizza - домашняя кухня',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body>
        <Providers>
          <AppHeader />
          {children}
        </Providers>
      </body>
    </html>
  );
}
